---
title: "Garch Fit"
output: html_document
date: "2024-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Data Preprocessing

## Load the required packages
```{r}
library(quantmod)
library(tidyverse)
library(Hmisc)
library(moments)
library(reshape2)
library(fGarch)
library(keras)
library(tensorflow)
```

## Define the stock symbol and date range
```{r}
tickers <- c("AAPL", "AMGN", "AXP", "BA", "CAT", "CRM", "CSCO", "CVX", "DIS", "DOW",
            "GS", "HD", "HON", "IBM", "INTC", "JNJ", "JPM", "KO", "MCD", "MMM",
            "MRK", "MSFT", "NKE", "PG", "TRV", "UNH", "V", "VZ", "WBA", "WMT")
start_date <- as.Date("2000-01-01")
end_date <- as.Date("2020-12-31")
```

## Fetch the stock prices
```{r}
closing_prices <- lapply(tickers, function(ticker) {
  getSymbols(ticker, src = 'yahoo', from = start_date, to = end_date, auto.assign = FALSE)[,6]
})

closing_prices <- as_tibble(do.call(cbind, closing_prices))

date <- index(getSymbols("AAPL", src = 'yahoo', from = start_date, to = end_date, auto.assign = FALSE))
closing_prices <- cbind(date, closing_prices)

# Remove columns with NA & clean column names
closing_prices <- closing_prices[ , colSums(is.na(closing_prices))==0]

names(closing_prices)[-1] <- substr(names(closing_prices)[-1], 1, nchar(names(closing_prices)[-1]) - 9)

# Calculate daily returns
daily_returns <- closing_prices %>%
  mutate_at(vars(-1), ~log(.) - log(lag(.))) %>%
  na.omit()

days <- nrow(daily_returns)

daily_returns_long <- pivot_longer(daily_returns, cols = -1, names_to = "ticker", values_to = "returns")
```

## Fit Individual $Garch(1, 1)$ Models
```{r}
get_garch_fit <- function(stock, end_date) {
  tmp <- daily_returns_long %>% filter(date <= end_date, ticker == stock)
  fit <- garchFit(formula = ~ garch(1, 1), data = tmp$returns, trace = FALSE)
  return(tail(fit@sigma.t, n = 1))
}

garch_fit_results <- data.frame(
  date = integer(),
  ticker = character(),
  fitted_sigma = double()
)

#dates_test <- dates[1:10]
for (d in dates) {
  x <- get_garch_fit("DIS", d)
  garch_fit_results[nrow(garch_fit_results) + 1,] <- c(d, "DIS", x)
}

write.csv(garch_fit_results, "garch_fit_results_AAPL_DIS.csv")
```
